-- Admin audit trail and sold-state reporting.
create table if not exists public.admin_access_log (
  id bigint generated by default as identity primary key,
  admin_email text not null,
  accessed_at timestamptz not null default now()
);

alter table public.admin_access_log enable row level security;
revoke all on public.admin_access_log from anon, authenticated;

create or replace function public.admin_dashboard_report()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if caller_email = '' or coalesce(auth.jwt() ->> 'email_confirmed_at', '') = '' or not exists (
    select 1 from public.admin_users where lower(email) = caller_email
  ) then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  insert into public.admin_access_log (admin_email) values (caller_email);

  return jsonb_build_object(
    'members', coalesce((
      select jsonb_agg(to_jsonb(m) order by m.joined desc)
      from (select id, name, email, town, premium, joined from public.members order by joined desc) m
    ), '[]'::jsonb),
    'threads', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.created_at desc)
      from (select id, title, body, town, author, posted_by, created_at from public.forum_threads order by created_at desc) t
    ), '[]'::jsonb),
    'listings', coalesce((
      select jsonb_agg(to_jsonb(l) order by l.created_at desc)
      from (select id, title, price, cond, category, description, town, author, posted_by, sold, sold_at, created_at from public.market_listings order by created_at desc) l
    ), '[]'::jsonb),
    'reports', coalesce((
      select jsonb_agg(to_jsonb(r) order by r.created_at desc)
      from (select id, target_type, target_id, reason, details, reported_by, created_at from public.reports order by created_at desc) r
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.admin_dashboard_report() from public;
revoke execute on function public.notify_matching_saved_filters() from public, anon, authenticated;
grant execute on function public.admin_dashboard_report() to authenticated;
